export const fieldObjects = {
  signInPage:{
    formName: 'login-form',
    firstFieldType: "text",
    labelOneName: "Email",
    labelTwoName: "Password",
    placeholderOne: "Email",
    placeholderTwo: "Password",
    formOneName: "email-login",
    formOneAutocomplete: "email",
    formTwoName: "password-login",
    formTwoAutocomplete: "password",
    buttonText: 'Sign in'
},
signUpPage:{
  formName: "sign-up-form",
  firstFieldType: "text",
  labelOneName: "Email",
  labelTwoName: "Password",
  labelThreeName: "Nickname",
  labelFourName: "Join group",
  labelFiveName: "Create new group",
  labelSixName: "Group name",
  labelSevenName: "Upload profile picture",
  placeholderOne: "We won't spam, don' worry",
  placeholderTwo: "Select a strong password",
  placeholderThree: "Nickname must be unique",
  placeholderFour: "Enter ID of the group you want to join",
  placeholderSix: "Enter group name",
  formOneName: "email-sign-up",
  formOneAutocomplete: "email",
  formTwoName: "password-sign-up",
  formTwoAutocomplete: "current-password",
  formThreeName: "nickname-sign-up",
  formThreeAutocomplete: "nickname",
  formFourName: "existing-bet-group",
  formFourAutocomplete: "bet-id",
  formFiveName: "create-new-group",
  formSixName: "new-group-name",
  formSixAutocomplete: "group-name",
  formSevenName: "upload-profile-picture",
  formSevenAutocomplete: "profile picture",
  buttonText: "Sign Up"
}
};